### ISSUE TITLE
Issue with Incremental.conf 

### ISSUE THREAD

**Issue by Khandelwal12** [redouane-dev/sync-elasticsearch-mysql#1]
Hi Redouane, 

I am trying to index data using this (incremental.conf) configuration, but I am not seeing any expected result, what exactly happening is that, while executing update statement in MySql, I am getting the new data after updation and older data as well on elasticsearch. I am not really getting how is this possible, and also ran delete operation in MySql but it is not working as expected on Elasticsearch.    
I also did index data using from-scratch.conf but the data is not fully indexed (Checking logs for this but could not find anything concrete). Thanks

 Best Regards, 
Yash

**Comment by r13i** [comment]
Hi!

Could you provide the scripts you are using and your execution context?

It would be better if you open up an issue on github and provide the
details there.

Best,
Redouane
